import { styled } from '@ignite-shop/styles'
import Head from 'next/head'

const Button = styled('button', {
  backgroundColor: '$rocketseat',
  border: 'none',
  padding: '1rem',
  borderRadius: 8,
  color: 'white',
  fontSize: '1.5rem',
  transition: 'all 0.2s ease-in-out',
  '&:hover': {
    backgroundColor: 'red',
    cursor: 'pointer',
  },
  '&:active': {
    backgroundColor: 'blue',
    cursor: 'pointer',
  },
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>coco</h1>
        <Button>Me clique</Button>
      </main>
    </>
  )
}
